spring.application.name=movie-rater
server.port=8080

firebase.database.url=${FIREBASE_DATABASE_URL:https://movieratermobile-default-rtdb.europe-west1.firebasedatabase.app/}
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:}

imdb.api.url=${IMDB_API_URL:https://api.imdbapi.dev}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs